on:
  push:
    branches:
    - main

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Clojure
        # You may pin to the exact commit or the version.
        # uses: DeLaGuardo/setup-clojure@0fc99a3bcdd086349bfb01a9262382fe3d37cd6d
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          cli: true
